CREATE TABLE Customers (
    CustomerID NUMBER PRIMARY KEY,
    CustomerName VARCHAR2(50),
    Age NUMBER,
    Balance NUMBER,
    IsVIP VARCHAR2(10)
);

CREATE TABLE Loans (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    InterestRate NUMBER,
    DueDate DATE,
    FOREIGN KEY (CustomerID)
    REFERENCES Customers(CustomerID)
);

INSERT INTO Customers VALUES (101,'Ravi',65,15000,'FALSE');
INSERT INTO Customers VALUES (102,'Priya',45,8000,'FALSE');
INSERT INTO Customers VALUES (103,'Kumar',70,20000,'FALSE');

INSERT INTO Loans VALUES (501,101,10,SYSDATE+15);
INSERT INTO Loans VALUES (502,102,12,SYSDATE+45);
INSERT INTO Loans VALUES (503,103,11,SYSDATE+20);

COMMIT;